### PR TITLE
Chrome extension integration, woo!

### PR DESCRIPTION
**Pull request by Inumedia**
Chrome extension + my functionality.

Global mass is visible
Small mini map in top right of window, near leader board.

### CODE REVIEW

**Comment by Irraquated** [comment]
Good work to say the least, @Inumedia but there is one problem, I believe this should be a separate mod because as soon as the minimap, show all mass, etc. is added we cannot advertise this "mod" on the reddit. Due to the rule ``Do not post cheats or anything else that might give one an unfair advantage. Posts like this will be taken down immediately and the user will receive a 3 day ban``. But I do believe we could make this into a separate mod @electronoob ?

**Comment by electronoob** [comment]
if this merge is met with a ton of resistance then we can rethink the situation. What I will be doing is attempting to merge in your changes, without using the main_out.js file that had to be hacked to make these mods work. I would rather patch on the fly than us host essentially a copy of the guys code, albeit obfuscated and freely world readable anyway.

**Comment by Inumedia** [comment]
I'm skeptical that such a method could work, but if you get something that does I'd be very interested in seeing it.

**Comment by electronoob** [comment]
Okies, I've created /Intercept/ on the repo which demo's the new system for patching the game like I mentioned earlier. I would really appreciate it if you can start porting your mods over for inclusion.

**Pull request merged**
